### ISSUE TITLE
Training time rquired to train the MoEL model

### ISSUE THREAD

**Issue by aysha1302** [HLTCHKUST/MoEL#4]
Sir,
I am running the program in Colab.It get stucks while training .Could you pls tell how much time needed to train the MoEL model?
 Kindly help

**Comment by zlinao** [comment]
should be less than half day by using a single 1080Ti GPU

**Comment by aysha1302** [comment]
Thank you sir..I would also like to know how to run the preprocessing code seperately.When i try to run it,it shows the error:
Traceback (most recent call last):
  File "/content/gdrive/My Drive/MoEL-master/get_ed_data.py", line 298, in <module>
    parser = setup_args()
  File "/content/gdrive/My Drive/MoEL-master/get_ed_data.py", line 104, in setup_args
    parser.add_pytorch_datateacher_args()
AttributeError: 'ParlaiParser' object has no attribute 'add_pytorch_datateacher_args'

**Comment by aysha1302** [comment]
Thank you sir..I would also like to know how to run the preprocessing code
seperately.When i try to run it,it shows the error:
Traceback (most recent call last):
File "/content/gdrive/My Drive/MoEL-master/get_ed_data.py", line 298, in
parser = setup_args()
File "/content/gdrive/My Drive/MoEL-master/get_ed_data.py", line 104, in
setup_args
parser.add_pytorch_datateacher_args()
AttributeError: 'ParlaiParser' object has no attribute
'add_pytorch_datateacher_args'




Thanks in advance

**Comment by aysha1302** [comment]
Thank you sir..I would also like to know how to run the preprocessing code
seperately.When i try to run it,it shows the error:
Traceback (most recent call last):
File "/content/gdrive/My Drive/MoEL-master/get_ed_data.py", line 298, in
parser = setup_args()
File "/content/gdrive/My Drive/MoEL-master/get_ed_data.py", line 104, in
setup_args
parser.add_pytorch_datateacher_args()
AttributeError: 'ParlaiParser' object has no attribute
'add_pytorch_datateacher_args'

Thank you in advance
